image:
  registry: docker-registry-test.lab.zjvis.net:32443/docker.io
  repository: bitnami/phpmyadmin
  tag: 5.1.1-debian-10-r147
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: phpmyadmin-nebula-test.lab.zjvis.net
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: false
db:
  allowArbitraryServer: true
metrics:
  image:
    registry: docker-registry-test.lab.zjvis.net:32443/docker.io
    repository: bitnami/apache-exporter
    tag: 0.10.1-debian-10-r54
    pullPolicy: IfNotPresent
