persistence:
  storageClass: "rook-cephfs-01"
  size: 4Gi
cluster:
  nodes: 6
image:
  registry: docker-registry-test.lab.zjvis.net:32443/docker.io
  repository: bitnami/redis-cluster
  tag: 6.2.2-debian-10-r0
  pullPolicy: IfNotPresent
metrics:
  image:
    registry: docker-registry-test.lab.zjvis.net:32443/docker.io
    repository: bitnami/redis-exporter
    tag: 1.20.0-debian-10-r27
    pullPolicy: IfNotPresent
volumePermissions:
  enabled: false
  image:
    registry: docker-registry-test.lab.zjvis.net:32443/docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
service:
  type: NodePort